### ISSUE TITLE
IJKMediaFramework.framework具体放到哪个文件夹呢？

### ISSUE THREAD

**Issue by leebaoshan** [LYM-mg/MGMiaoBo#2]
我试了好几个文件夹都报错，提示：'IJKMediaFramework/IJKMediaFramework.h' file not found

**Comment by LYM-mg** [comment]
我github的有解释怎么解决这个问题，你应该没有看这个项目的介绍，直接下载就运行项目了。你应该先去文件夹中找到ijk…包（如果找不到请去我的github那里找到，那里有百度云盘分享），解压ijk…包，然后拖入项目。
具体放哪个文件夹关系不大，拖去入项目，运行即可。我一般放项目最顶层，如下图：

![如图.png](http://upload-images.jianshu.io/upload_images/1429890-5bdbcf683e8fd0e2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
